services:
  db:
    image: mysql:8.0
    container_name: booooomb-mysql
    restart: always
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: "1234"
      MYSQL_DATABASE: "mydb"
    command:
      - --character-set-server=utf8mb4
      - --collation-server=utf8mb4_unicode_ci
    volumes:
      - ./database/datadir/:/var/lib/mysql
      - ./database/init/:/docker_entrypoint-initdb.d/